CREATE TABLE Critere (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE Destination (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    urlimage VARCHAR(255),
    ville VARCHAR(255),
    description VARCHAR(255),
    score INT,
    budget DECIMAL(10, 2)
);

CREATE TABLE Utilisateur (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pseudo VARCHAR(255),
    motdepasse VARCHAR(255),
    mail VARCHAR(255)
);

CREATE TABLE Activite (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE Newsletter (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail VARCHAR(255) NOT NULL
)