INSERT INTO Critere(nom) VALUES 
('Mer'),
('Montagne'),
('Campagne'),
('Plage'),
('Culture'),
('Art'),
('Nature'),
('Sports'),
('Gastronomie'),
('Aventure'),
('Découverte'),
('Détente'),
('Croisière'),
('Escapade maritime'),
('camping'),
('Hiver'),
('Printemps'),
('Été'),
('Automone'),
('Week-end'),
('semaine'),
('semaines'),
('Populaires et touristiques'),
('Moins connus et plus authentiques'),
('Amérique'),
('Europe'),
('Asie'),
('Antartique'),
('Afrique'),
('Océnie'),
('Économique'),
('Milieu de gamme'),
('Luxe'),
('Solo'),
('En couple'),
('Famille'),
('Groupe');